using System;
using System.Collections.Generic;
using DG.Tweening;
using UnityEngine;

namespace AlienDefense.Towers
{
    /// <summary>Purely visual "build from the bottom up" reveal played once when a tower is bought. For the length
    /// of the build it swaps every tower renderer onto a matching AlienDefense/TowerBuildReveal material (edit-time
    /// copies of the originals, so no runtime material instances), feeds one shared world-space height range and the
    /// animated progress through a MaterialPropertyBlock, and then puts the original URP/Lit materials back and
    /// clears the block - after that the tower renders and batches exactly as it did before this component existed.
    ///
    /// Owns no gameplay: the tower is fully active the whole time (colliders, targeting and attacks are untouched).</summary>
    [DisallowMultipleComponent]
    public sealed class TowerConstructionVFX : MonoBehaviour
    {
        [Serializable]
        public struct MaterialPair
        {
            public Material Original;
            public Material Build;
        }

        private static readonly int BuildProgressId = Shader.PropertyToID("_BuildProgress");
        private static readonly int BuildBaseYId = Shader.PropertyToID("_BuildBaseY");
        private static readonly int BuildHeightId = Shader.PropertyToID("_BuildHeight");
        private static readonly int BuildEdgeColorId = Shader.PropertyToID("_BuildEdgeColor");
        private static readonly int BuildEdgeWidthId = Shader.PropertyToID("_BuildEdgeWidth");
        private static readonly int BuildEdgeIntensityId = Shader.PropertyToID("_BuildEdgeIntensity");
        private static readonly int BuildNoiseScaleId = Shader.PropertyToID("_BuildNoiseScale");
        private static readonly int BuildNoiseAmountId = Shader.PropertyToID("_BuildNoiseAmount");
        private static readonly int BuildPulseId = Shader.PropertyToID("_BuildPulse");

        [Header("Setup")]
        [SerializeField]
        [Tooltip("Only MeshRenderers / SkinnedMeshRenderers under this transform are built. Point it at the tower's " +
            "model, never at the tower root - the range indicator and any world UI must not dissolve.")]
        private Transform _visualRoot;

        [SerializeField]
        [Tooltip("Original URP/Lit material -> its AlienDefense/TowerBuildReveal copy. Generated by " +
            "AlienDefense/Setup/Towers/Setup Construction VFX.")]
        private MaterialPair[] _materialPairs = Array.Empty<MaterialPair>();

        [SerializeField]
        [Tooltip("Optional. Cyan sparks that ride the construction line. Must not live under the Visual Root.")]
        private ParticleSystem _constructionParticles;

        [Header("Timing")]
        [SerializeField, Range(0.3f, 3f)]
        private float _buildDuration = 1.1f;

        [SerializeField]
        [Tooltip("InOutSine keeps the line moving steadily; OutCubic front-loads the base. Never Bounce/Elastic.")]
        private Ease _buildEase = Ease.InOutSine;

        [SerializeField, Range(0f, 0.5f)]
        [Tooltip("Soft cyan glow over the whole tower right after the line clears the top.")]
        private float _completePulseDuration = 0.15f;

        [Header("Look")]
        [SerializeField, ColorUsage(false, true)]
        private Color _edgeColor = new Color(0.306f, 0.961f, 1f); // #4EF5FF

        [SerializeField, Range(0.005f, 0.2f)]
        private float _edgeWidth = 0.05f;

        [SerializeField, Range(0f, 8f)]
        private float _edgeIntensity = 2.5f;

        [SerializeField, Min(0f)]
        private float _noiseScale = 4f;

        [SerializeField, Range(0f, 0.15f)]
        [Tooltip("0 = perfectly straight construction line.")]
        private float _noiseAmount = 0.03f;

        [SerializeField]
        private bool _useParticles = true;

        [SerializeField]
        [Tooltip("Master switch. Off = PlayConstruction does nothing and the tower just appears.")]
        private bool _effectEnabled = true;

        [Header("Debug (Play Mode)")]
        [SerializeField, Range(0f, 1f)]
        [Tooltip("Drag in Play Mode to scrub the reveal on this tower. Ignored while a build is animating.")]
        private float _previewProgress = 1f;

        private Renderer[] _renderers;
        private Material[][] _originalMaterials;
        private Material[][] _buildMaterials;
        private MaterialPropertyBlock _block;
        private Tween _buildTween;
        private Tween _pulseTween;
        private float _progress = 1f;
        private float _pulse;
        private float _baseY;
        private float _height = 1f;
        private bool _swapped;
        private bool _initialized;

        public bool IsPlaying { get; private set; }

        public float BuildDuration => _buildDuration;

        private void Awake()
        {
            EnsureInitialized();
        }

        public void PlayConstruction()
        {
            PlayConstruction(_buildDuration);
        }

        public void PlayConstruction(float duration)
        {
            if (!_effectEnabled || !EnsureInitialized() || _renderers.Length == 0)
            {
                return;
            }

            KillTweens();
            RecalculateBuildRange();
            SwapToBuildMaterials();

            IsPlaying = true;
            _pulse = 0f;
            _progress = 0f;
            ApplyBlock();
            StartParticles();

            _buildTween = DOTween.To(() => _progress, SetProgress, 1f, Mathf.Max(0.05f, duration))
                .SetEase(_buildEase)
                .SetLink(gameObject)
                .OnComplete(HandleBuildLineFinished);
        }

        /// <summary>Snaps to the finished tower: original materials, no property block, no particles.</summary>
        public void CompleteImmediately()
        {
            KillTweens();
            Finish();
        }

        /// <summary>Reserved for a lighter upgrade flourish; intentionally not wired to upgrades yet.</summary>
        public void PlayUpgradeEffect()
        {
        }

        private void SetProgress(float value)
        {
            _progress = value;
            ApplyBlock();
            MoveParticlesToLine();
        }

        private void HandleBuildLineFinished()
        {
            _buildTween = null;
            _progress = 1f;
            BurstParticles(atTop: true, count: 14);
            StopParticleEmission();

            if (_completePulseDuration <= 0f)
            {
                Finish();
                return;
            }

            _pulse = 1f;
            ApplyBlock();
            _pulseTween = DOTween.To(() => _pulse, v => { _pulse = v; ApplyBlock(); }, 0f, _completePulseDuration)
                .SetEase(Ease.OutQuad)
                .SetLink(gameObject)
                .OnComplete(Finish);
        }

        private void Finish()
        {
            _pulseTween = null;
            _buildTween = null;
            _progress = 1f;
            _pulse = 0f;
            RestoreOriginalMaterials();
            StopParticleEmission();
            IsPlaying = false;
        }

        private bool EnsureInitialized()
        {
            if (_initialized)
            {
                return true;
            }

            if (_visualRoot == null)
            {
                Debug.LogWarning("[TowerConstructionVFX] No Visual Root assigned - construction effect disabled.", this);
                return false;
            }

            var found = new List<Renderer>();
            foreach (Renderer candidate in _visualRoot.GetComponentsInChildren<Renderer>(true))
            {
                if (candidate is MeshRenderer || candidate is SkinnedMeshRenderer)
                {
                    found.Add(candidate);
                }
            }

            _renderers = found.ToArray();
            _originalMaterials = new Material[_renderers.Length][];
            _buildMaterials = new Material[_renderers.Length][];

            for (int r = 0; r < _renderers.Length; r++)
            {
                Material[] originals = _renderers[r].sharedMaterials;
                var builds = new Material[originals.Length];
                for (int slot = 0; slot < originals.Length; slot++)
                {
                    builds[slot] = FindBuildMaterial(originals[slot]);
                }

                _originalMaterials[r] = originals;
                _buildMaterials[r] = builds;
            }

            _block = new MaterialPropertyBlock();
            _initialized = true;
            return true;
        }

        private Material FindBuildMaterial(Material original)
        {
            if (original == null)
            {
                return null;
            }

            for (int i = 0; i < _materialPairs.Length; i++)
            {
                if (_materialPairs[i].Original == original && _materialPairs[i].Build != null)
                {
                    return _materialPairs[i].Build;
                }
            }

            Debug.LogWarning($"[TowerConstructionVFX] '{original.name}' has no build material; that part will pop in " +
                "instead of being built. Re-run AlienDefense/Setup/Towers/Setup Construction VFX.", this);
            return original;
        }

        /// <summary>One world-space range for the whole tower, so every part shares a single continuous reveal.</summary>
        private void RecalculateBuildRange()
        {
            Bounds bounds = _renderers[0].bounds;
            for (int i = 1; i < _renderers.Length; i++)
            {
                bounds.Encapsulate(_renderers[i].bounds);
            }

            _baseY = bounds.min.y;
            _height = Mathf.Max(0.01f, bounds.size.y);

            if (_constructionParticles != null)
            {
                ParticleSystem.ShapeModule shape = _constructionParticles.shape;
                shape.radius = Mathf.Max(0.2f, Mathf.Max(bounds.extents.x, bounds.extents.z) * 0.9f);
                Vector3 center = bounds.center;
                _constructionParticles.transform.position = new Vector3(center.x, _baseY, center.z);
            }
        }

        private void SwapToBuildMaterials()
        {
            if (_swapped)
            {
                return;
            }

            for (int i = 0; i < _renderers.Length; i++)
            {
                if (_renderers[i] != null)
                {
                    _renderers[i].sharedMaterials = _buildMaterials[i];
                }
            }

            _swapped = true;
        }

        private void RestoreOriginalMaterials()
        {
            if (!_swapped)
            {
                return;
            }

            for (int i = 0; i < _renderers.Length; i++)
            {
                if (_renderers[i] == null)
                {
                    continue;
                }

                _renderers[i].SetPropertyBlock(null);
                _renderers[i].sharedMaterials = _originalMaterials[i];
            }

            _swapped = false;
        }

        private void ApplyBlock()
        {
            _block.SetFloat(BuildProgressId, _progress);
            _block.SetFloat(BuildBaseYId, _baseY);
            _block.SetFloat(BuildHeightId, _height);
            _block.SetColor(BuildEdgeColorId, _edgeColor);
            _block.SetFloat(BuildEdgeWidthId, _edgeWidth);
            _block.SetFloat(BuildEdgeIntensityId, _edgeIntensity);
            _block.SetFloat(BuildNoiseScaleId, _noiseScale);
            _block.SetFloat(BuildNoiseAmountId, _noiseAmount);
            _block.SetFloat(BuildPulseId, _pulse);

            for (int i = 0; i < _renderers.Length; i++)
            {
                if (_renderers[i] != null)
                {
                    _renderers[i].SetPropertyBlock(_block);
                }
            }
        }

        private void StartParticles()
        {
            if (!_useParticles || _constructionParticles == null)
            {
                return;
            }

            _constructionParticles.Clear(true);
            _constructionParticles.Play(true);
            BurstParticles(atTop: false, count: 10); // small start flash on the build node
        }

        private void MoveParticlesToLine()
        {
            if (!_useParticles || _constructionParticles == null)
            {
                return;
            }

            Transform t = _constructionParticles.transform;
            Vector3 p = t.position;
            p.y = _baseY + Mathf.Clamp01(_progress) * _height;
            t.position = p;
        }

        private void BurstParticles(bool atTop, int count)
        {
            if (!_useParticles || _constructionParticles == null)
            {
                return;
            }

            Transform t = _constructionParticles.transform;
            Vector3 p = t.position;
            p.y = atTop ? _baseY + _height : _baseY;
            t.position = p;
            _constructionParticles.Emit(count);
        }

        private void StopParticleEmission()
        {
            if (_constructionParticles != null && _constructionParticles.isPlaying)
            {
                _constructionParticles.Stop(true, ParticleSystemStopBehavior.StopEmitting);
            }
        }

        private void KillTweens()
        {
            _buildTween?.Kill();
            _buildTween = null;
            _pulseTween?.Kill();
            _pulseTween = null;
        }

        private void OnDisable()
        {
            // Pooled / deactivated mid-build: never come back half built or stuck on the build materials.
            if (IsPlaying)
            {
                CompleteImmediately();
            }
        }

        private void OnDestroy()
        {
            KillTweens();
        }

#if UNITY_EDITOR
        private void OnValidate()
        {
            if (!Application.isPlaying || !_initialized || IsPlaying || _renderers == null || _renderers.Length == 0)
            {
                return;
            }

            if (_previewProgress >= 0.999f)
            {
                RestoreOriginalMaterials();
                return;
            }

            RecalculateBuildRange();
            SwapToBuildMaterials();
            _progress = _previewProgress;
            _pulse = 0f;
            ApplyBlock();
        }

        [ContextMenu("Preview Construction (Play Mode)")]
        private void PreviewConstruction()
        {
            if (Application.isPlaying)
            {
                PlayConstruction();
            }
            else
            {
                Debug.Log("[TowerConstructionVFX] Enter Play Mode to preview the construction.", this);
            }
        }

        [ContextMenu("Complete Immediately")]
        private void ContextCompleteImmediately()
        {
            if (Application.isPlaying)
            {
                CompleteImmediately();
            }
        }
#endif
    }
}
